
DROP FUNCTION IF EXISTS fn_role_id;

DELIMITER $$
CREATE FUNCTION fn_role_id(p_code VARCHAR(40)) RETURNS SMALLINT UNSIGNED
  READS SQL DATA
BEGIN
  DECLARE v_id SMALLINT UNSIGNED;
  SELECT id INTO v_id FROM roles WHERE code = p_code;
  RETURN v_id;
END$$
DELIMITER ;
